### ISSUE TITLE
Trouble with degree sign

### ISSUE THREAD

**Issue by ritamsaha00** [closebox73/Orion#2]
First of all, I love your work. My desktop would look like it traveled through time from the past without your themes.
About my issue, everything works perfectly except for a little ditty. There is an unwanted character before the degree sign and I don't know how to fix it.
![Screenshot from 2022-08-27 18-22-10](https://user-images.githubusercontent.com/69363775/187044339-08dc1490-5e99-45ef-a0a9-f609cb2948fe.png)
N.B. - I have tried different fonts as well, but it still doesn't work.

**Comment by closebox73** [comment]
thank you for using the theme that I made, for that problem so far I haven't found a solution, I don't think it's in the font used, because not everyone has this problem

**Comment by ritamsaha00** [comment]
Yes, adding that line at the end of config did the trick. Thanks man, really appreciate it.
![Screenshot from 2022-09-13 01-32-25](https://user-images.githubusercontent.com/69363775/189745854-5183bee5-5bd2-4089-aca8-d50d5120d599.png)
