### ISSUE TITLE
Weird border shadow

### ISSUE THREAD

**Issue by Morphy-Kun** [closebox73/Orion#3]
First of all, love the theme, as well as all your other works. I'm getting this weird shadow on the border of the window. No clue why. I'm using cinnamon DE. Any suggestions? 

![image](https://user-images.githubusercontent.com/44739457/196588546-59b267e9-bf62-4037-8c41-ed25c7e54bbb.png)

**Comment by closebox73** [comment]
thank you for using the theme that I made, for this I will find out, because this is the first time this has happened, and I have never used cinnamon

**Comment by Morphy-Kun** [comment]
Figured out the issue. By setting `own_window_argb_visual = true`
the shadow disappeared.
